### ISSUE TITLE
Swagger UI link broken

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/OSLC-API#1]
Hi,

The link in to Swagger UI (http://oslc-ui.mybluemix.net/) in https://github.com/OSLC/OSLC-API/blob/master/README.md returns the following error:

> failed to parse JSON/YAML response

By default, the page tried to parse http://oslc-ui.mybluemix.net/swagger.yaml. The file itself is not missing.

This is the Chrome dev console:

```
resolver.js:736   cannot parse JSON/YAML content
(index):85        Unable to Load SwaggerUI
```

**Comment by berezovskyi** [comment]
Testing from http://petstore.swagger.io/ gives the following:

> Can't read from server. It may not have the appropriate access-control-origin settings.

**Comment by berezovskyi** [comment]
This one is from a long time ago. Can you investigate who holds the acct credentials, please?

**Comment by jamsden** [comment]
All the above links are working now. Maybe there was an issue with Bluemix. However, the Bluemix projects that were deployed to these routes are owned by Neil Davis. I'm getting them transferred to me.
